workflows:
  android-aab:
    name: Build Android AAB
    max_build_duration: 120
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @bubblewrap/cli
      - name: Build AAB
        script: |
          cd /home/builder/work/Sellam_bot/Sellam_bot
          bubblewrap build
    artifacts:
      - app-release.aab
    publishing:
      email:
        recipients:
          - xzervzxs@gmail.com
