workflows:
  android-aab:
    name: Build Android AAB
    max_build_duration: 120
    triggering:
      events:
        - push
    scripts:
      - name: Build AAB
        script: |
          chmod +x build_aab.sh
          ./build_aab.sh
    artifacts:
      - app-release.aab
      - app-release-signed.apk
    publishing:
      email:
        recipients:
          - xzervzxs@gmail.com
